### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by Tragen** [Shadowsith/mattermost-plugin-videofile#3]
I'm using Mattermost Version: 7.10.0 currently self hosted.
I've uploaded your plugin and enabled it but when I upload an mp4, nothing happens.
Everything looks like before.

![image](https://github.com/Shadowsith/mattermost-plugin-videofile/assets/1700241/cdbe9ea5-c7ad-4d6a-ab3a-5d4f1011250e)

![image](https://github.com/Shadowsith/mattermost-plugin-videofile/assets/1700241/03de5f67-05c3-4b52-93b9-6c969a4aa201)

What can I do and check why it is not working?

**Comment by JeroenAdam** [comment]
Same here, v1.1.1 of this plugin installed and enabled on Mattermost v9.0,0.
No embedded video player shows up for an uploaded .webm file.
Tried in a channel and tried in a thread.
Your other plugin mattermost-videourl-plugin works fine, thanks for that!
![image](https://github.com/Shadowsith/mattermost-plugin-videofile/assets/16437621/ae2f3a85-6c6b-4ecc-99b7-dbc25750f108)

**Comment by Shadowsith** [comment]
Thanks for the reports. Since we are still using Mattermost 8.x on our server, I can't repoduce the errors yet. I will have a look at the problem with a Mattermost 9.x version locally in the near future. I suspect Mattermost has made some changes to their frontend API that I need to read up on.

**Comment by Tragen** [comment]
This has nothing to do with v9.x.
It didn't work since 7.10 as in my first post.
8.x didn't work and it still doesn't work with 9.x

**Comment by danilvalov** [comment]
@Shadowsith I reseached this problem and fixed it here: https://github.com/Shadowsith/mattermost-plugin-videofile/pull/4
Could you merge it and release a new version with this fix?

**Comment by Shadowsith** [comment]
@danilvalov thank you for analyzing the error, version [1.1.2](https://github.com/Shadowsith/mattermost-plugin-videofile/releases/tag/1.1.2) is now released has been tested on a Mattermost v9.5.0 server. 

![grafik](https://github.com/Shadowsith/mattermost-plugin-videofile/assets/22940789/3950c0c3-e251-49b0-892b-bc5e2ec13c2c)
